### ISSUE TITLE
Escaped Quote Breaks Highlighting

### ISSUE THREAD

**Issue by WhatIsHeDoing** [aarongraham/splunk-syntax-sublime#1]
Hi,

I've installed the syntax highlighter, which has been really helpful.  However, it currently does not cater for an escaped quote, i.e. `"\""`, which will break the highlighting for the rest of the document from that point.

Thanks,
Darren

**Comment by aarongraham** [comment]
Thanks for submitting the issue. I have just committed a fix. I'm not sure how long it takes for the package manager to pick up the new version, but after you have tried it out let me know if you have any more problems.

**Comment by WhatIsHeDoing** [comment]
Wow, thanks for the prompt response and fix, appreciate it!

-----Original Message-----
